### ISSUE TITLE
DB user/pass

### ISSUE THREAD

**Issue by mikedoubintchik** [nbyloff/trellis-backup#1]
I think that lines 45-46 here: https://github.com/nbyloff/trellis-backup/blob/master/tasks/main.yml

Need to be updated to:
```
backup_mysql_user: "{{ site_env.db_user }}"
backup_mysql_pass: "{{ site_env.db_password }}"
```

I was getting an error that those variables didn't exist

**Comment by nbyloff** [comment]
Sorry I missed these messages, thank you for doing them. This has been updated
