### ISSUE TITLE
Multisite issue

### ISSUE THREAD

**Issue by mikedoubintchik** [nbyloff/trellis-backup#2]
I'm not sure if this is solely due to multisite, but I'm not having any issue provisioning my non-multisite server. The error I receive:

```
TASK [trellis-backup : Create uploads purge job] *******************************
System info:
  Ansible 2.2.1.0; Darwin
  Trellis at "Forward extra bin/deploy.sh parameters to ansible-playbook"
---------------------------------------------------
MODULE FAILURE
Traceback (most recent call last):
  File "/tmp/ansible_FHVRjQ/ansible_module_cron.py", line 714, in <module>
    main()
  File "/tmp/ansible_FHVRjQ/ansible_module_cron.py", line 682, in main
    crontab.write()
  File "/tmp/ansible_FHVRjQ/ansible_module_cron.py", line 288, in write
    fileh = open(self.cron_file, 'w')
IOError: [Errno 13] Permission denied: '/etc/cron.d/purge'

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: IOError: [Errno 13] Permission denied: '/etc/cron.d/purge'
failed: [104.236.36.135] (item=allureprojects.com) => {"failed": true, "item": "allureprojects.com", "module_stdout": ""}
        to retry, use: --limit @/Users/mike/Sites/Development/DO-AllureWebSolutions-1/trellis/server.retry

```

**Comment by rolandp** [comment]
Ran into the same problem. 

After some debugging I noticed that contrary to other Ansible tasks this task did not have a 'become' attribute. This attribute is responsible for a privilege escalation, see [the ansible docs](http://docs.ansible.com/ansible/latest/become.html)

So the server.yml file should contain this:
```- name: Set up backups
  hosts: web:&{{ env }}
  become: yes
  roles:
    - { role: trellis-backup, tags: [backup] }
    - { role: Stouts.backup, tags: [backup] }
```
Notice the addition of `become: yes`

**Comment by nbyloff** [comment]
Sorry I missed all of this. I have become: yes in my server.yml files already by default. I can add this statement to each of the 3 tasks in this role if it makes it easier, but otherwise I'll close.

Edit: nvm. I need to update the instructions. Doing now.
